### ISSUE TITLE
Too good

### ISSUE THREAD

**Issue by DextreminiDev** [Oxyuraa/TurtleBasedDatahandlerThingy#1]
idk
why
am
i
writing
this
in
a
issue
but
there
are
no
issues
in
this
repo
cuz
it
too
good
to
be
in
this
world

**Comment by Oxyuraa** [comment]
> idk
> why
> am
> i
> writing
> this
> in
> a
> issue
> but
> there
> are
> no
> issues
> in
> this
> repo
> cuz
> it
> too
> good
> to
> be
> in
> this
> world

limau
